# Generated by Django 3.0.4 on 2020-04-02 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200401_2127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
