# Generated by Django 3.0.4 on 2020-04-03 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='project',
        ),
    ]
