# Generated by Django 3.0.4 on 2020-04-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0002_delete_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('summary', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('body', models.CharField(max_length=250)),
                ('pub_date', models.DateTimeField()),
            ],
        ),
    ]
